apiVersion: apps/v1
kind: Deployment
metadata:
  name: gijirock-redis
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gijirock-redis
      app.kubernetes.io/version: "0.1"
      app.kubernetes.io/component: kvs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gijirock-redis
        app.kubernetes.io/version: "0.1"
        app.kubernetes.io/component: kvs
    spec:
      containers:
      - name: redis
        resources:
          requests:
            cpu: 100m
            memory: 132M
          limits:
            cpu: 200m
            memory: 256M
        image: redis
        ports:
        - containerPort: 6379
